import { ProjectConfig } from "../types/index.js";

/**
 * DockerignoreGenerator class - Generates comprehensive .dockerignore
 */
export class DockerignoreGenerator {
	constructor(private config: ProjectConfig) {}

	generate(language?: string): string {
		const ignorePatterns: string[] = [
			"# ============================================",
			"# Comprehensive .dockerignore",
			"# Generated by Dockeryzen",
			"# ============================================",
			"",
			"# Version Control",
			".git",
			".gitignore",
			".gitattributes",
			".github",
			".gitlab",
			".svn",
			".hg",
			"",
			"# IDE",
			".vscode",
			".idea",
			"*.swp",
			"*.swo",
			"*~",
			".project",
			".classpath",
			".settings",
			"*.sublime-workspace",
			"*.sublime-project",
			"",
			"# OS",
			".DS_Store",
			"Thumbs.db",
			"desktop.ini",
			"",
			"# Environment",
			".env",
			".env.local",
			".env.development.local",
			".env.test.local",
			".env.production.local",
			".env.*",
			"!.env.example",
			"",
			"# Secrets",
			"secrets/",
			"*.pem",
			"*.key",
			"*.crt",
			"*.p12",
			"*.pfx",
			"credentials.json",
			"service-account.json",
			"",
			"# Logs",
			"logs/",
			"*.log",
			"npm-debug.log*",
			"yarn-debug.log*",
			"yarn-error.log*",
			"pnpm-debug.log*",
			"lerna-debug.log*",
			"",
			"# Temp files",
			"tmp/",
			"temp/",
			"*.tmp",
			"*.temp",
			"*.bak",
			"*.swp",
			"*.swo",
			"",
			"# Documentation",
			"README.md",
			"LICENSE",
			"*.md",
			"docs/",
			"documentation/",
			"",
			"# Testing",
			"coverage/",
			".nyc_output/",
			".cache/",
			"*.spec.js",
			"*.test.js",
			"*.spec.ts",
			"*.test.ts",
			"__tests__/",
			".pytest_cache/",
			".coverage",
			"htmlcov/",
			".tox/",
			".nox/",
			".hypothesis/",
			"",
		];

		const lang = language || this.config.language;

		if (lang.startsWith("js")) {
			ignorePatterns.push("# Node.js", "node_modules/", ".npm/", ".node-gyp/", ".npmrc", ".pnpm-store/", ".yarn-integrity", ".yarn/", ".pnp.js", ".pnp.cjs", "dist/", "build/", ".next/", ".nuxt/", "out/", "coverage/", ".vite/", ".cache/", "");
		} else if (lang.startsWith("java")) {
			ignorePatterns.push("# Java", "target/", "*.class", "*.jar", "*.war", "*.ear", "*.log", ".mvn/", "mvnw", "mvnw.cmd", ".gradle/", "build/", ".settings/", ".classpath", ".project", "");
		} else if (lang === "python") {
			ignorePatterns.push(
				"# Python",
				"__pycache__/",
				"*.py[cod]",
				"*$py.class",
				"*.so",
				".Python",
				"env/",
				"venv/",
				"ENV/",
				"env.bak/",
				"venv.bak/",
				"pip-log.txt",
				".pytest_cache/",
				".coverage",
				"htmlcov/",
				".tox/",
				".nox/",
				".hypothesis/",
				".mypy_cache/",
				".pytype/",
				".pyre/",
				"dist/",
				"build/",
				"*.egg-info/",
				"",
			);
		} else if (lang === "go") {
			ignorePatterns.push("# Go", "*.exe", "*.exe~", "*.dll", "*.so", "*.dylib", "*.test", "*.out", "go.work", "bin/", "dist/", "vendor/", "");
		} else if (lang === "rust") {
			ignorePatterns.push("# Rust", "target/", "**/*.rs.bk", "Cargo.lock", "");
		} else if (lang === "dotnet") {
			ignorePatterns.push("# .NET", "**/[Oo]bj/", "**/[Bb]in/", "*.user", "*.suo", "*.userprefs", "*.cache", "*.docstates", "dist/", "build/", "packages/", "");
		} else if (lang === "laravel") {
			ignorePatterns.push("# PHP/Laravel", "vendor/", "*.log", ".phpunit.result.cache", "node_modules/", "public/storage", "storage/*.key", "storage/framework/cache/*", "storage/framework/sessions/*", "storage/framework/views/*", "");
		} else if (lang === "rails") {
			ignorePatterns.push("# Ruby/Rails", "*.gem", ".bundle/", "vendor/bundle/", "log/*", "tmp/*", ".ruby-version", ".ruby-gemset", "node_modules/", "public/assets/", "storage/", "");
		} else if (lang === "cpp" || lang === "c") {
			ignorePatterns.push("# C/C++", "*.o", "*.obj", "*.exe", "*.out", "*.app", "build/", "dist/", "cmake-build-*/", "CMakeFiles/", "CMakeCache.txt", "Makefile", "");
		}

		// Docker files (keep main files)
		ignorePatterns.push("# Docker (keep main files)", "docker-compose.*.yml", "docker-compose.*.yaml", ".docker/", "");

		return ignorePatterns.join("\n");
	}
}
