import { ProjectConfig } from "../types/index.js";

export class DockerignoreGenerator {
	constructor(private config: ProjectConfig) {}

	generate(): string {
		const ignorePatterns = [
			"# Version Control",
			".git",
			".gitignore",
			".gitattributes",
			"",
			"# IDE",
			".vscode",
			".idea",
			"*.swp",
			"*.swo",
			"*~",
			"",
			"# OS",
			".DS_Store",
			"Thumbs.db",
			"",
			"# Dependencies",
			"node_modules",
			"npm-debug.log*",
			"yarn-debug.log*",
			"yarn-error.log*",
			"pnpm-debug.log*",
			"",
			"# Build outputs",
			"dist",
			"build",
			"out",
			"target",
			"bin",
			"obj",
			"*.class",
			"*.jar",
			"*.war",
			"*.ear",
			"*.zip",
			"*.tar.gz",
			"*.rar",
			"",
			"# Python",
			"__pycache__",
			"*.py[cod]",
			"*$py.class",
			"*.so",
			".Python",
			"env",
			"venv",
			"ENV",
			"env.bak",
			"venv.bak",
			"pip-log.txt",
			"pip-delete-this-directory.txt",
			".pytest_cache",
			".coverage",
			".coverage.*",
			"htmlcov",
			".tox",
			".nox",
			".hypothesis",
			".mypy_cache",
			".pytype",
			".pyre",
			"",
			"# Node.js",
			".npm",
			".node-gyp",
			".npmrc",
			".pnpm-store",
			"npm-debug.log",
			"yarn-error.log",
			".pnpm-debug.log",
			".yarn-integrity",
			"",
			"# Java",
			"*.class",
			"*.log",
			"*.ctxt",
			".mtj.tmp",
			"hs_err_pid*",
			"replay_pid*",
			".mvn",
			"mvnw",
			"mvnw.cmd",
			".gradle",
			"gradle-app.setting",
			"!gradle-wrapper.jar",
			"!gradle-wrapper.properties",
			"",
			"# Go",
			"*.exe",
			"*.exe~",
			"*.dll",
			"*.so",
			"*.dylib",
			"*.test",
			"*.out",
			"go.work",
			"",
			"# Rust",
			"target/",
			"**/*.rs.bk",
			"",
			"# .NET",
			"**/[Oo]bj/",
			"**/[Bb]in/",
			"*.user",
			"*.suo",
			"*.userprefs",
			"*.cache",
			"*.docstates",
			"",
			"# Ruby",
			"*.gem",
			".bundle",
			"vendor/bundle",
			"log/*",
			"tmp/*",
			".ruby-version",
			".ruby-gemset",
			"",
			"# PHP",
			"vendor/",
			"*.log",
			".phpunit.result.cache",
			"",
			"# Environment",
			".env",
			".env.local",
			".env.development.local",
			".env.test.local",
			".env.production.local",
			"",
			"# Docker",
			"Dockerfile",
			"docker-compose.yml",
			"docker-compose.yaml",
			".dockerignore",
			"docker-compose.*.yml",
			"",
			"# Documentation",
			"README.md",
			"LICENSE",
			"*.md",
			"docs",
			"",
			"# Testing",
			"coverage",
			".nyc_output",
			".cache",
			"*.spec.js",
			"*.test.js",
			"",
			"# Logs",
			"logs",
			"*.log",
			"npm-debug.log*",
			"yarn-debug.log*",
			"yarn-error.log*",
			"pnpm-debug.log*",
			"lerna-debug.log*",
			"",
			"# Temp files",
			"tmp",
			"temp",
			"*.tmp",
			"*.temp",
			"",
			"# Optional: Remove or comment out if you need these files",
			"# .env",
			"# config.json",
			"# credentials.json",
			"# secrets.json",
		];

		return ignorePatterns.join("\n");
	}
}
