import { ProjectConfig } from "../types/index.js";

export class DockerignoreGenerator {
	constructor(private config: ProjectConfig) {}

	generate(language?: string): string {
		const ignorePatterns: string[] = [
			"# ============================================",
			"# Comprehensive .dockerignore",
			"# Generated by Dockeryzen",
			"# ============================================",
			"",
			"# Version Control",
			".git",
			".gitignore",
			".gitattributes",
			".gitlab",
			".svn",
			".hg",
			"",
			"# IDE",
			".vscode",
			".idea",
			"*.swp",
			"*.swo",
			"*~",
			".project",
			".classpath",
			".settings",
			"",
			"# OS",
			".DS_Store",
			"Thumbs.db",
			"desktop.ini",
			"",
			"# Environment",
			".env",
			".env.local",
			".env.development.local",
			".env.test.local",
			".env.production.local",
			".env.*",
			"!.env.example",
			"!.env.production",
			"!.env.development",
			"!.env.staging",
			"",
			"# Secrets",
			"secrets/",
			"*.pem",
			"*.key",
			"*.crt",
			"*.p12",
			"*.pfx",
			"credentials.json",
			"service-account.json",
			"",
			"# Logs",
			"logs/",
			"*.log",
			"npm-debug.log*",
			"yarn-debug.log*",
			"yarn-error.log*",
			"pnpm-debug.log*",
			"lerna-debug.log*",
			"",
			"# Temp files",
			"tmp/",
			"temp/",
			"*.tmp",
			"*.temp",
			"*.bak",
			"",
			"# Documentation",
			"README.md",
			"LICENSE",
			"*.md",
			"docs/",
			"",
			"# Testing",
			"coverage/",
			".nyc_output/",
			".cache/",
			"*.spec.js",
			"*.test.js",
			"*.spec.ts",
			"*.test.ts",
			"",
		];

		const lang = language || this.config.language;

		if (lang.startsWith("js")) {
			ignorePatterns.push("# Node.js", "node_modules/", ".npm/", ".node-gyp/", "dist/", "build/", "out/", ".next/cache/", ".nuxt/", ".output/", "");
		} else if (lang.startsWith("java")) {
			ignorePatterns.push("# Java", "target/", "*.class", "*.jar", "*.war", "*.ear", ".mvn/wrapper/maven-wrapper.jar", ".gradle/", "build/", "");
		} else if (lang === "python") {
			ignorePatterns.push("# Python", "__pycache__/", "*.py[cod]", "*$py.class", "*.so", ".Python", "env/", "venv/", "ENV/", ".pytest_cache/", ".mypy_cache/", "dist/", "build/", "*.egg-info/", "");
		} else if (lang === "go") {
			ignorePatterns.push("# Go", "*.exe", "*.exe~", "*.dll", "*.so", "*.dylib", "*.test", "*.out", "bin/", "dist/", "");
		} else if (lang === "rust") {
			ignorePatterns.push("# Rust", "target/", "**/*.rs.bk", "");
		} else if (lang === "dotnet") {
			ignorePatterns.push("# .NET", "**/[Oo]bj/", "**/[Bb]in/", "*.user", "*.suo", "dist/", "build/", "");
		} else if (lang === "laravel") {
			ignorePatterns.push("# PHP/Laravel", "vendor/", ".phpunit.result.cache", "node_modules/", "public/storage", "");
		} else if (lang === "rails") {
			ignorePatterns.push("# Ruby/Rails", "*.gem", ".bundle/", "vendor/bundle/", "log/*", "tmp/*", "node_modules/", "storage/", "");
		} else if (lang === "cpp" || lang === "c") {
			ignorePatterns.push("# C/C++", "*.o", "*.obj", "*.exe", "*.out", "build/", "dist/", "cmake-build-*/", "");
		}

		ignorePatterns.push("# Docker (keep main files including override)", "docker-compose.*.yml", "!docker-compose.yml", "!docker-compose.override.yml", "docker-compose.*.yaml", "!docker-compose.yaml", "!docker-compose.override.yaml", ".docker/", "");

		return ignorePatterns.join("\n");
	}
}
