import { ProjectConfig } from "../types/index.js";

export class DockerfileGenerator {
	constructor(
		private config: ProjectConfig,
		private langConfig?: any,
	) {}

	generate(): string {
		switch (this.config.language) {
			case "java-jar":
				return this.generateJavaJarDockerfile();
			case "java-war":
				return this.generateJavaWarDockerfile();
			case "js-frontend":
				return this.generateJSFrontendDockerfile();
			case "js-backend":
				return this.generateJSBackendDockerfile();
			case "python":
				return this.generatePythonDockerfile();
			case "go":
				return this.generateGoDockerfile();
			case "rust":
				return this.generateRustDockerfile();
			case "dotnet":
				return this.generateDotNetDockerfile();
			case "laravel":
				return this.generateLaravelDockerfile();
			case "rails":
				return this.generateRailsDockerfile();
			case "cpp":
				return this.generateCppDockerfile();
			case "c":
				return this.generateCDockerfile();
			default:
				return this.generateGenericDockerfile();
		}
	}

	private getDebugPort(): string {
		if (this.config.debugPort) return this.config.debugPort.toString();
		const lang = this.config.language;
		if (lang.startsWith("java")) return "5005";
		if (lang.startsWith("js")) return "9229";
		if (lang === "python") return "5678";
		if (lang === "dotnet") return "5000";
		if (lang === "go") return "2345";
		if (lang === "laravel") return "9003";
		if (lang === "rails") return "1234";
		if (lang === "cpp" || lang === "c") return "1234";
		return "";
	}

	private getDebugExpose(): string {
		if (!this.config.enableDebug) return "";
		const debugPort = this.getDebugPort();
		if (!debugPort) return "";
		return `\n# Debug port\nEXPOSE ${debugPort}`;
	}

	private getHealthCheck(): string {
		if (!this.config.enableHealthCheck) return "";
		const healthPath = this.config.healthCheckPath || "/health";
		const port = this.config.port;
		const lang = this.config.language;

		if (lang === "java-war") {
			// باگ 545: Java WAR از healthCheckPath استفاده میکنه
			const checkPath = this.config.healthCheckPath || "/";
			return `\n# Health check\nHEALTHCHECK --interval=30s --timeout=3s --start-period=30s --retries=3 \\\n  CMD curl -f http://localhost:${port}${checkPath} || exit 1`;
		}

		if (lang === "python" && this.config.useAlpine) {
			return `\n# Health check\nHEALTHCHECK --interval=30s --timeout=3s --start-period=30s --retries=3 \\\n  CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:${port}${healthPath}')" || exit 1`;
		}

		if (lang === "laravel") {
			// باگ 546: Laravel از پورت اصلی استفاده میکنه
			return `\n# Health check\nHEALTHCHECK --interval=30s --timeout=3s --start-period=30s --retries=3 \\\n  CMD php -r "echo @file_get_contents('http://localhost:${port}${healthPath}') ? 'ok' : exit(1);" || exit 1`;
		}

		if (this.config.useAlpine) {
			return `\n# Health check\nHEALTHCHECK --interval=30s --timeout=3s --start-period=30s --retries=3 \\\n  CMD wget -q --spider http://localhost:${port}${healthPath} || exit 1`;
		}

		return `\n# Health check\nHEALTHCHECK --interval=30s --timeout=3s --start-period=30s --retries=3 \\\n  CMD curl -f http://localhost:${port}${healthPath} || exit 1`;
	}

	private getInstallCommand(): string {
		// باگ 547: wget ممکنه نباشه، از curl استفاده میکنیم
		if (this.config.useAlpine) {
			return "RUN apk add --no-cache curl ca-certificates";
		}
		return "RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates && rm -rf /var/lib/apt/lists/*";
	}

	private getOciLabels(): string {
		const labels = [`org.opencontainers.image.title="${this.config.projectName}"`, `org.opencontainers.image.description="Generated by Dockeryzen"`, `org.opencontainers.image.version="1.0.0"`, `org.opencontainers.image.created="${new Date().toISOString()}"`];
		return `# OCI Labels\nLABEL ${labels.join(" \\\n      ")}`;
	}

	private generateJavaJarDockerfile(): string {
		const baseImage = this.getJavaBaseImage();
		const buildStage = this.getJavaBuildStage();
		const debugExpose = this.getDebugExpose();
		const healthCheck = this.getHealthCheck();
		const healthCheckInstall = this.config.enableHealthCheck ? `\n# Install health check tools\n${this.getInstallCommand()}\n` : "";
		const ociLabels = this.getOciLabels();

		// باگ 681: jar path برای Gradle اصلاح شد
		const jarPath = this.config.buildTool === "gradle" ? "/app/build/libs/*.jar" : "/app/target/*.jar";

		let profileEnv = "";
		if (this.config.framework === "quarkus") {
			profileEnv = `ENV QUARKUS_PROFILE=prod`;
		} else if (this.config.framework === "micronaut") {
			profileEnv = `ENV MICRONAUT_ENVIRONMENTS=prod`;
		} else {
			profileEnv = `ENV SPRING_PROFILES_ACTIVE=production`;
		}

		const jvmOpts = ["-Xms512m", "-Xmx1024m", "-XX:+UseG1GC", "-XX:MaxGCPauseMillis=200", "-XX:+ExitOnOutOfMemoryError", "-XX:+UseContainerSupport", "-XX:MaxRAMPercentage=75.0"];
		if (this.config.enableDebug) {
			jvmOpts.push("-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005");
		}

		return `# syntax=docker/dockerfile:1.4

# Build stage
${buildStage}

# Runtime stage
FROM ${baseImage}

WORKDIR /app
${healthCheckInstall}
# Copy JAR from build stage
COPY --from=build ${jarPath} app.jar

# Create non-root user
${this.config.useAlpine ? "RUN adduser -D -u 1001 appuser && chown -R appuser:appuser /app" : "RUN useradd -r -u 1001 -g root appuser && chown -R appuser:root /app && chmod -R 755 /app"}

USER appuser

${ociLabels}

${profileEnv}

# Expose application port
EXPOSE ${this.config.port}${debugExpose}${healthCheck}

# Run application with JVM tuning
# باگ 531: JAVA_OPTS فقط اینجا تعریف میشه
ENV JAVA_OPTS="${jvmOpts.join(" ")}"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]`;
	}

	private generateJavaWarDockerfile(): string {
		// باگ 532: jetty دیگه به tomcat تبدیل نمیشه
		const server = this.config.server || "tomcat";
		const serverImage = this.getServerImage(server);
		const debugExpose = this.getDebugExpose();
		const healthCheck = this.getHealthCheck();
		const healthCheckInstall = this.config.enableHealthCheck ? `\n# Install health check tools\nRUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates && rm -rf /var/lib/apt/lists/*\n` : "";
		const ociLabels = this.getOciLabels();

		const isJetty = server === "jetty";
		// باگ 610: Jetty webapps path اصلاح شد
		const webappsPath = isJetty ? "/var/lib/jetty/webapps" : "/usr/local/tomcat/webapps";
		const startCommand = isJetty ? '["/usr/local/jetty/bin/jetty.sh", "run"]' : '["catalina.sh", "run"]';
		const warPath = this.config.buildTool === "gradle" ? "/app/build/libs/*.war" : "/app/target/*.war";

		let catalinaOpts = "";
		if (this.config.enableDebug) {
			catalinaOpts = `\n# Debug configuration for Tomcat\nENV CATALINA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"`;
		}

		return `# syntax=docker/dockerfile:1.4

# Build stage
${this.getJavaBuildStage()}

# Runtime stage
FROM ${serverImage}

WORKDIR /app
${healthCheckInstall}
# Copy WAR file
COPY --from=build ${warPath} ${webappsPath}/ROOT.war
${catalinaOpts}

${ociLabels}

# Expose application port
EXPOSE ${this.config.port}${debugExpose}${healthCheck}

# Start server
CMD ${startCommand}`;
	}

	private getServerImage(server: string): string {
		const version = this.config.jdkVersion || "17";
		const useAlpine = this.config.useAlpine;
		if (version === "8" && useAlpine) {
			return "tomcat:8.5-jre8";
		}
		if (this.langConfig?.types) {
			const warConfig = this.langConfig.types.find((t: any) => t.type === "java-war");
			if (warConfig?.servers) {
				const serverConfig = warConfig.servers.find((s: any) => s.value === server);
				if (serverConfig) {
					if (useAlpine && serverConfig.alpineImages?.[version]) {
						return serverConfig.alpineImages[version];
					}
					if (serverConfig.images?.[version]) {
						return serverConfig.images[version];
					}
				}
			}
		}
		const variant = useAlpine ? "-alpine" : "";
		if (server === "tomcat") {
			const tomcatVersions: Record<string, string> = { "8": "8.5-jre8", "11": "9.0-jre11", "17": "10.1-jre17", "21": "10.1-jre21", "25": "10.1-jre21" };
			return `tomcat:${tomcatVersions[version] || "10.1-jre17"}${variant}`;
		} else {
			const jettyVersions: Record<string, string> = { "8": "9.4-jre8", "11": "11.0-jre11", "17": "11.0-jre17", "21": "12.0-jre21", "25": "12.0-jre21" };
			return `jetty:${jettyVersions[version] || "11.0-jre17"}${variant}`;
		}
	}

	private getJavaBuildStage(): string {
		let version = this.config.jdkVersion || "17";
		// باگ 533: JDK 25 با Maven/Gradle ناسازگار
		if (version === "25" && this.config.buildTool === "gradle") version = "21";
		if (version === "25" && this.config.buildTool === "maven") version = "21";
		const useAlpine = this.config.useAlpine;

		if (this.config.buildTool === "gradle") {
			const gradleVersion = version === "8" ? "7" : "8";
			const image = `gradle:${gradleVersion}-jdk${version}${useAlpine ? "-alpine" : ""}`;
			return `FROM ${image} AS build
WORKDIR /app

COPY build.gradle* settings.gradle* gradlew* ./
RUN if [ -d gradle ]; then cp -r gradle ./gradle; fi
COPY src ./src

RUN --mount=type=cache,target=/root/.gradle/caches \\
    if [ -f gradlew ]; then ./gradlew build -x test --no-daemon; else gradle build -x test --no-daemon; fi`;
		} else {
			let image: string;
			if (version === "8") {
				image = "maven:3.9-eclipse-temurin-8";
			} else {
				image = `maven:3.9-eclipse-temurin-${version}${useAlpine ? "-alpine" : ""}`;
			}
			return `FROM ${image} AS build
WORKDIR /app

COPY pom.xml ./
RUN if [ -d .mvn ]; then cp -r .mvn .mvn; fi
RUN if [ -f mvnw ]; then cp mvnw* ./; fi

RUN --mount=type=cache,target=/root/.m2 \\
    if [ -f mvnw ]; then ./mvnw package -DskipTests; else mvn package -DskipTests; fi`;
		}
	}

	private getJavaBaseImage(): string {
		const vendor = this.config.jdkVendor || "eclipse-temurin";
		let version = this.config.jdkVersion || "17";
		// باگ 636: JDK 25 با eclipse-temurin ممکنه tag نداشته باشه
		if (version === "25" && vendor === "eclipse-temurin") {
			version = "21";
		}

		if (this.langConfig?.jdkVendors) {
			const vendorConfig = this.langConfig.jdkVendors.find((v: any) => v.value === vendor);
			if (vendorConfig) {
				if (this.config.useAlpine && vendorConfig.jreAlpineImages?.[version]) return vendorConfig.jreAlpineImages[version];
				if (vendorConfig.jreImages?.[version]) return vendorConfig.jreImages[version];
				if (this.config.useAlpine && vendorConfig.jdkAlpineImages?.[version]) return vendorConfig.jdkAlpineImages[version];
				if (vendorConfig.jdkImages?.[version]) return vendorConfig.jdkImages[version];
			}
		}
		const variant = this.config.useAlpine ? "-alpine" : "";
		const imageMap: Record<string, string> = {
			"eclipse-temurin": `eclipse-temurin:${version}-jre${variant}`,
			amazoncorretto: `amazoncorretto:${version}${variant}`,
			openjdk: `openjdk:${version}${variant ? "-alpine" : "-slim"}`,
			"azul-zulu": `azul/zulu-openjdk:${version}${variant ? "-alpine" : ""}`,
		};
		return imageMap[vendor] || imageMap["eclipse-temurin"];
	}

	private getNodeImage(version: string): string {
		if (this.langConfig?.versions) {
			const versionConfig = this.langConfig.versions.find((v: any) => v.value === version);
			if (versionConfig?.images) {
				if (this.config.useAlpine && versionConfig.images.alpine) return versionConfig.images.alpine;
				if (versionConfig.images.standard) return versionConfig.images.standard;
			}
		}
		return `node:${version}${this.config.useAlpine ? "-alpine" : ""}`;
	}

	private getPackageInstallCommand(): string {
		const pm = this.config.packageManager || "npm";
		switch (pm) {
			case "yarn":
				return "yarn install --frozen-lockfile";
			case "pnpm":
				return "pnpm install --frozen-lockfile";
			case "bun":
				return "bun install";
			case "deno":
				return "deno cache --reload";
			default:
				return "npm ci || npm install";
		}
	}

	private generateJSFrontendDockerfile(): string {
		const nodeVersion = this.config.nodeVersion || "18";
		const image = this.getNodeImage(nodeVersion);
		const debugExpose = this.getDebugExpose();
		const healthCheck = this.getHealthCheck();
		const healthCheckInstall = this.config.enableHealthCheck ? `\n# Install health check tools\n${this.getInstallCommand()}\n` : "";
		const ociLabels = this.getOciLabels();
		const framework = this.config.framework;
		const installCmd = this.getPackageInstallCommand();
		const isAlpineUser = this.config.useAlpine ? "RUN adduser -D -u 1001 appuser && chown -R appuser:appuser /app" : "RUN useradd -r -u 1001 -g root appuser && chown -R appuser:root /app";

		if (framework === "angular") {
			return `# syntax=docker/dockerfile:1.4

# Build stage
FROM ${image} AS build
WORKDIR /app
COPY package*.json yarn.lock* pnpm-lock.yaml* bun.lockb* ./
RUN --mount=type=cache,target=/root/.npm ${installCmd}
COPY . .
RUN npm run build

# Runtime stage
FROM ${image}
WORKDIR /app
${healthCheckInstall}
ENV NODE_ENV=production
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./
${isAlpineUser}
USER appuser
${ociLabels}
EXPOSE ${this.config.port}${debugExpose}${healthCheck}
# باگ 534: Angular CMD اصلاح شد
CMD ["node", "dist/server/main.js"]`;
		} else if (framework === "nuxtjs") {
			return `# syntax=docker/dockerfile:1.4

# Build stage
FROM ${image} AS build
WORKDIR /app
COPY package*.json yarn.lock* pnpm-lock.yaml* bun.lockb* ./
RUN --mount=type=cache,target=/root/.npm ${installCmd}
COPY . .
RUN npm run build

# Runtime stage
FROM ${image}
WORKDIR /app
${healthCheckInstall}
ENV NODE_ENV=production
ENV PORT=${this.config.port}
COPY --from=build /app/.nuxt ./.nuxt
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./
COPY --from=build /app/public ./public
COPY --from=build /app/nuxt.config.* ./
${isAlpineUser}
USER appuser
${ociLabels}
EXPOSE ${this.config.port}${debugExpose}${healthCheck}
# باگ 535: Nuxt CMD اصلاح شد
CMD ["npm", "run", "start"]`;
		} else {
			return `# syntax=docker/dockerfile:1.4

# Build stage
FROM ${image} AS build
WORKDIR /app
COPY package*.json yarn.lock* pnpm-lock.yaml* bun.lockb* ./
RUN --mount=type=cache,target=/root/.npm ${installCmd}
COPY . .
# باگ 696: sharp فقط برای Next.js
RUN if [ -f next.config.js ] || [ -f next.config.mjs ]; then npm install sharp || true; fi
RUN if grep -q '"output": "export"' next.config.* 2>/dev/null; then \\
        npm run build && npx next export -o out; \\
    else \\
        npm run build; \\
    fi

# Runtime stage
FROM ${image}
WORKDIR /app
${healthCheckInstall}
ENV NODE_ENV=production
ENV PORT=${this.config.port}
COPY --from=build /app/.next ./.next
COPY --from=build /app/out ./out
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./
COPY --from=build /app/public ./public
COPY --from=build /app/next.config.* ./
${isAlpineUser}
USER appuser
${ociLabels}
EXPOSE ${this.config.port}${debugExpose}${healthCheck}
CMD ["npm", "start"]`;
		}
	}

	private generateJSBackendDockerfile(): string {
		const nodeVersion = this.config.nodeVersion || "18";
		const image = this.getNodeImage(nodeVersion);
		const debugExpose = this.getDebugExpose();
		const healthCheck = this.getHealthCheck();
		const healthCheckInstall = this.config.enableHealthCheck ? `\n# Install health check tools\n${this.getInstallCommand()}\n` : "";
		const ociLabels = this.getOciLabels();
		const installCmd = this.getPackageInstallCommand();
		const isAlpineUser = this.config.useAlpine ? "RUN adduser -D -u 1001 appuser && chown -R appuser:appuser /app" : "RUN useradd -r -u 1001 -g root appuser && chown -R appuser:root /app";

		// باگ 536: pm2 نصب به صورت global
		const pm2Install = this.config.enablePm2 ? "RUN npm install -g pm2\n" : "";
		const pm2Cmd = this.config.enablePm2 ? 'CMD ["pm2-runtime", "start", "dist/index.js", "--name", "app"]' : 'CMD ["node", "dist/index.js"]';

		return `# syntax=docker/dockerfile:1.4

FROM ${image}
WORKDIR /app
${healthCheckInstall}
COPY package*.json yarn.lock* pnpm-lock.yaml* bun.lockb* tsconfig.json* ./
RUN --mount=type=cache,target=/root/.npm ${installCmd}
${pm2Install}
COPY . .
# باگ 646: خطا دیگر پنهان نمیشه
RUN if [ -f tsconfig.json ]; then npm run build; fi
RUN npm cache clean --force || true
${isAlpineUser}
USER appuser
ENV NODE_ENV=production
ENV PORT=${this.config.port}
${ociLabels}
EXPOSE ${this.config.port}${debugExpose}${healthCheck}
${pm2Cmd}`;
	}

	private getPythonImage(version: string): string {
		if (this.langConfig?.versions) {
			const versionConfig = this.langConfig.versions.find((v: any) => v.value === version);
			if (versionConfig?.images) {
				if (this.config.useAlpine && versionConfig.images.alpine) return versionConfig.images.alpine;
				if (versionConfig.images.slim) return versionConfig.images.slim;
				if (versionConfig.images.standard) return versionConfig.images.standard;
			}
		}
		return `python:${version}${this.config.useAlpine ? "-alpine" : "-slim"}`;
	}

	private generatePythonDockerfile(): string {
		const pythonVersion = this.config.pythonVersion || "3.11";
		const image = this.getPythonImage(pythonVersion);
		const debugExpose = this.getDebugExpose();
		const healthCheck = this.getHealthCheck();
		const healthCheckInstall = this.config.enableHealthCheck ? `\n# Install health check tools\n${this.getInstallCommand()}\n` : "";
		const ociLabels = this.getOciLabels();
		const framework = this.config.framework;
		const useVirtualEnv = this.config.useVirtualEnv;
		const useGunicorn = this.config.enableGunicorn;
		const isAlpineUser = this.config.useAlpine ? "RUN adduser -D -u 1001 appuser && chown -R appuser:appuser /app" : "RUN useradd -r -u 1001 -g root appuser && chown -R appuser:root /app";

		const installCmd = this.config.useAlpine ? "RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev zlib-dev jpeg-dev freetype-dev lcms2-dev" : "RUN apt-get update && apt-get install -y --no-install-recommends gcc libpq-dev default-libmysqlclient-dev libjpeg-dev && rm -rf /var/lib/apt/lists/*";

		// باگ 612: virtualenv path با Alpine سازگار شد
		const virtualEnvSetup = useVirtualEnv
			? `
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"`
			: "";

		let extraPackages = "";
		if (useGunicorn || framework === "django" || framework === "flask") {
			extraPackages = "gunicorn";
		}
		if (framework === "fastapi") {
			// باگ 537: Gunicorn با uvicorn conflict نداره
			extraPackages = extraPackages ? `${extraPackages} "uvicorn[standard]"` : '"uvicorn[standard]"';
		}

		let startCmd = 'CMD ["python", "app.py"]';
		if (framework === "django") {
			if (useGunicorn) {
				startCmd = `CMD ["gunicorn", "--bind", "0.0.0.0:${this.config.port}", "--workers", "4", "--timeout", "120", "--preload", "config.wsgi:application"]`;
			} else {
				startCmd = `CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:${this.config.port}"]`;
			}
		} else if (framework === "flask") {
			if (useGunicorn) {
				startCmd = `CMD ["gunicorn", "--bind", "0.0.0.0:${this.config.port}", "--workers", "4", "--preload", "app:app"]`;
			} else {
				startCmd = `CMD ["flask", "run", "--host=0.0.0.0", "--port=${this.config.port}"]`;
			}
		} else if (framework === "fastapi") {
			startCmd = `CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${this.config.port}", "--workers", "4", "--loop", "uvloop", "--http", "httptools"]`;
		}

		return `# syntax=docker/dockerfile:1.4

# Build stage
FROM ${image} AS build
WORKDIR /app
${installCmd}
COPY requirements.txt* pyproject.toml* setup.py* ./
RUN --mount=type=cache,target=/root/.cache/pip \\
    pip install --no-cache-dir --prefix=/install -r requirements.txt 2>/dev/null || \\
    pip install --no-cache-dir --prefix=/install . 2>/dev/null || true
${extraPackages ? `RUN pip install --no-cache-dir --prefix=/install ${extraPackages}` : ""}

# Runtime stage
FROM ${image}
WORKDIR /app
${healthCheckInstall}
${virtualEnvSetup}
COPY --from=build /install /usr/local
COPY . .
RUN python -m compileall -q . || true
RUN pip cache purge || true
${isAlpineUser}
USER appuser
ENV PYTHONUNBUFFERED=1 \\
    PYTHONDONTWRITEBYTECODE=1
${ociLabels}
EXPOSE ${this.config.port}${debugExpose}${healthCheck}
${startCmd}`;
	}

	private generateGoDockerfile(): string {
		const goVersion = this.config.goVersion || "1.21";
		const debugExpose = this.getDebugExpose();
		const healthCheck = this.getHealthCheck();
		const healthCheckInstall = this.config.enableHealthCheck ? `\n# Install health check tools\n${this.getInstallCommand()}\n` : "";
		const ociLabels = this.getOciLabels();
		const cgoEnabled = this.config.cgoEnabled !== false;

		let buildImage = `golang:${goVersion}`;
		if (this.langConfig?.versions) {
			const versionConfig = this.langConfig.versions.find((v: any) => v.value === goVersion);
			if (versionConfig) {
				buildImage = this.config.useAlpine ? versionConfig.alpineImage || versionConfig.image : versionConfig.image;
			}
		}

		const runtimeBase = this.config.useAlpine ? "alpine:latest" : "debian:bookworm-slim";
		const cgoFlag = cgoEnabled ? "1" : "0";
		const isAlpineUser = this.config.useAlpine ? "RUN adduser -D -u 1001 appuser && chown -R appuser:appuser /app" : "RUN useradd -r -u 1001 -g root appuser && chown -R appuser:root /app";

		// باگ 548: CGO packages فقط وقتی CGO فعاله
		const cgoPackages = this.config.useAlpine && cgoEnabled ? "RUN apk add --no-cache gcc musl-dev libc6-compat" : "";

		return `# syntax=docker/dockerfile:1.4

# Build stage
FROM ${buildImage} AS build
WORKDIR /app
${cgoPackages}
ARG GOPROXY=https://proxy.golang.org,direct
ARG GOPRIVATE=
COPY go.mod go.sum* ./
# باگ 689: go mod download با go.sum اختیاری
RUN --mount=type=cache,target=/go/pkg/mod \\
    go mod download 2>/dev/null || go mod tidy && go mod download
COPY . .
# باگ 613: installsuffix cgo حذف شد
RUN CGO_ENABLED=${cgoFlag} GOOS=linux go build -a -ldflags="-s -w -X main.version=1.0.0" -o main .

# Runtime stage
FROM ${runtimeBase}
WORKDIR /app
${this.config.useAlpine ? "RUN apk --no-cache add ca-certificates tzdata curl" : "RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates tzdata curl && rm -rf /var/lib/apt/lists/*"}
COPY --from=build /app/main .
RUN mkdir -p /app/static /app/templates /app/config 2>/dev/null || true
${isAlpineUser}
USER appuser
${ociLabels}
EXPOSE ${this.config.port}${debugExpose}${healthCheck}
CMD ["./main"]`;
	}

	private generateRustDockerfile(): string {
		const rustVersion = this.config.rustVersion || "latest";
		let buildImage = `rust:${rustVersion}`;
		if (this.langConfig?.versions) {
			const versionConfig = this.langConfig.versions.find((v: any) => v.value === rustVersion);
			if (versionConfig) {
				if (this.config.useAlpine) {
					buildImage = versionConfig.buildAlpineImage || versionConfig.buildImage;
				} else {
					buildImage = versionConfig.buildSlimImage || versionConfig.buildImage;
				}
			}
		}
		const runtimeImage = this.config.useAlpine ? "alpine:latest" : "debian:bookworm-slim";
		const isAlpineUser = this.config.useAlpine ? "RUN adduser -D -u 1001 appuser && chown -R appuser:appuser /app" : "RUN useradd -r -u 1001 -g root appuser && chown -R appuser:root /app";
		const ociLabels = this.getOciLabels();
		const healthCheckInstall = this.config.enableHealthCheck ? `\n${this.getInstallCommand()}\n` : "";

		// باگ 549: projectName با dash
		const safeBinaryName = this.config.projectName.replace(/[^a-zA-Z0-9_]/g, "_");

		return `# syntax=docker/dockerfile:1.4

# Build stage
FROM ${buildImage} AS build
WORKDIR /app
${this.config.useAlpine ? "RUN apk add --no-cache musl-dev pkgconfig openssl-dev" : ""}
COPY Cargo.toml Cargo.lock* ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build --release
# باگ 539: rm -rf src حذف شد
COPY . .
ARG RUSTFLAGS="-C strip=symbols"
# باگ 614: touch حذف شد
RUN --mount=type=cache,target=/usr/local/cargo/registry \\
    RUSTFLAGS="$RUSTFLAGS" cargo build --release

# Runtime stage
FROM ${runtimeImage}
WORKDIR /app
${this.config.useAlpine ? "RUN apk --no-cache add ca-certificates" : "RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*"}
${healthCheckInstall}
COPY --from=build /app/target/release/${safeBinaryName} .
${isAlpineUser}
USER appuser
${ociLabels}
EXPOSE ${this.config.port}${this.getHealthCheck()}
CMD ["./${safeBinaryName}"]`;
	}

	private generateDotNetDockerfile(): string {
		const dotnetVersion = this.config.dotnetVersion || "8.0";
		const debugExpose = this.getDebugExpose();
		const healthCheck = this.getHealthCheck();
		const healthCheckInstall = this.config.enableHealthCheck ? `\n# Install health check tools\n${this.getInstallCommand()}\n` : "";
		const ociLabels = this.getOciLabels();

		let sdkImage = `mcr.microsoft.com/dotnet/sdk:${dotnetVersion}`;
		let aspnetImage = `mcr.microsoft.com/dotnet/aspnet:${dotnetVersion}`;
		if (this.langConfig?.versions) {
			const versionConfig = this.langConfig.versions.find((v: any) => v.value === dotnetVersion);
			if (versionConfig) {
				sdkImage = versionConfig.sdkImage || sdkImage;
				aspnetImage = this.config.useAlpine ? versionConfig.aspnetAlpineImage || versionConfig.aspnetImage : versionConfig.aspnetImage;
			}
		}

		// باگ 550: dash تبدیل به underscore
		const safeProjectName = this.config.projectName.replace(/[^a-zA-Z0-9_]/g, "_");
		const isAlpineUser = this.config.useAlpine ? "RUN adduser -D -u 1001 appuser && chown -R appuser:appuser /app" : "RUN useradd -r -u 1001 -g root appuser && chown -R appuser:root /app";

		return `# syntax=docker/dockerfile:1.4

# Build stage
FROM ${sdkImage} AS build
WORKDIR /app
COPY *.csproj ./
# باگ 675: *.sln اختیاری
COPY *.sln* ./
COPY NuGet.config* nuget.config* ./
RUN --mount=type=cache,target=/root/.nuget/packages \\
    dotnet restore
COPY . .
# باگ 637: self-contained حذف شد
RUN dotnet publish -c Release -o out

# Runtime stage
FROM ${aspnetImage}
WORKDIR /app
${healthCheckInstall}
COPY --from=build /app/out .
${isAlpineUser}
USER appuser
${ociLabels}
EXPOSE ${this.config.port}${debugExpose}${healthCheck}
ENTRYPOINT ["dotnet", "${safeProjectName}.dll"]`;
	}

	private generateLaravelDockerfile(): string {
		const phpVersion = this.config.phpVersion || "8.3";
		const debugExpose = this.getDebugExpose();
		const healthCheck = this.getHealthCheck();
		const healthCheckInstall = this.config.enableHealthCheck ? `\n# Install health check tools\n${this.getInstallCommand()}\n` : "";
		const ociLabels = this.getOciLabels();

		let phpImage = `php:${phpVersion}-fpm`;
		if (this.langConfig?.versions) {
			const versionConfig = this.langConfig.versions.find((v: any) => v.value === phpVersion);
			if (versionConfig?.images) {
				phpImage = this.config.useAlpine ? versionConfig.images.fpmAlpine || versionConfig.images.fpm : versionConfig.images.fpm;
			}
		}

		const installCmd = this.config.useAlpine ? `RUN apk add --no-cache git curl libpng-dev oniguruma-dev libxml2-dev zip unzip supervisor` : `RUN apt-get update && apt-get install -y --no-install-recommends git curl libpng-dev libonig-dev libxml2-dev zip unzip supervisor && rm -rf /var/lib/apt/lists/*`;

		// باگ 541: supervisor config اختیاری
		const queueWorkerConfig = this.config.enableQueueWorker
			? `
COPY docker/supervisor/queue-worker.conf /etc/supervisor/conf.d/queue-worker.conf 2>/dev/null || true`
			: "";

		return `# syntax=docker/dockerfile:1.4

FROM ${phpImage}
WORKDIR /var/www/html
${installCmd}
# باگ 683: docker-php-ext-install با fallback
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd 2>/dev/null || \\
    docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
COPY . .
RUN --mount=type=cache,target=/root/.composer/cache \\
    composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist && \\
    composer dump-autoload --optimize --no-dev --classmap-authoritative

RUN mkdir -p /var/www/html/storage/framework/views \\
    /var/www/html/storage/framework/cache \\
    /var/www/html/storage/framework/sessions \\
    /var/www/html/bootstrap/cache

RUN chown -R www-data:www-data /var/www/html && \\
    chmod -R 755 /var/www/html/storage && \\
    chmod -R 755 /var/www/html/bootstrap/cache
${queueWorkerConfig}
${ociLabels}
EXPOSE 9000${debugExpose}${healthCheck}
CMD ["php-fpm"]`;
	}

	private generateRailsDockerfile(): string {
		const rubyVersion = this.config.rubyVersion || "3.3";
		const debugExpose = this.getDebugExpose();
		const healthCheck = this.getHealthCheck();
		const healthCheckInstall = this.config.enableHealthCheck ? `\n# Install health check tools\n${this.getInstallCommand()}\n` : "";
		const ociLabels = this.getOciLabels();

		let rubyImage = `ruby:${rubyVersion}`;
		if (this.langConfig?.versions) {
			const versionConfig = this.langConfig.versions.find((v: any) => v.value === rubyVersion);
			if (versionConfig?.images) {
				if (this.config.useAlpine && versionConfig.images.alpine) rubyImage = versionConfig.images.alpine;
				else if (versionConfig.images.slim) rubyImage = versionConfig.images.slim;
				else rubyImage = versionConfig.images.standard;
			}
		}

		const isAlpineUser = this.config.useAlpine ? "RUN adduser -D -u 1001 appuser && chown -R appuser:appuser /app" : "RUN useradd -r -u 1001 -g root appuser && chown -R appuser:root /app";
		const sidekiqConfig = this.config.enableSidekiq
			? `
RUN gem install sidekiq`
			: "";

		return `# syntax=docker/dockerfile:1.4

# Build stage
FROM ${rubyImage} AS build
WORKDIR /app
${this.config.useAlpine ? "RUN apk add --no-cache build-base postgresql-dev nodejs yarn tzdata git" : "RUN apt-get update && apt-get install -y --no-install-recommends build-essential libpq-dev nodejs yarn tzdata git && rm -rf /var/lib/apt/lists/*"}
COPY Gemfile Gemfile.lock* ./
# باگ 616: bundle install بدون flag منسوخ
RUN --mount=type=cache,target=/usr/local/bundle \\
    gem install bundler && bundle config set without 'development test' && bundle install
COPY . .
# باگ 694: assets:precompile اختیاری
RUN RAILS_ENV=production bundle exec rake assets:precompile 2>/dev/null || true

# Runtime stage
FROM ${rubyImage}
WORKDIR /app
${healthCheckInstall}
COPY --from=build /app /app
COPY --from=build /usr/local/bundle /usr/local/bundle
${sidekiqConfig}
${isAlpineUser}
USER appuser
ENV RAILS_ENV=production \\
    RAILS_SERVE_STATIC_FILES=true
${ociLabels}
EXPOSE ${this.config.port}${debugExpose}${healthCheck}
# باگ 542: ENTRYPOINT اصلاح شد
CMD ["sh", "-c", "bundle exec rails db:migrate && bundle exec puma -b tcp://0.0.0.0:${this.config.port}"]`;
	}

	private generateCppDockerfile(): string {
		const gccVersion = this.config.gccVersion || "13";
		const debugExpose = this.getDebugExpose();
		const healthCheck = this.getHealthCheck();
		const healthCheckInstall = this.config.enableHealthCheck ? `\n# Install health check tools\n${this.getInstallCommand()}\n` : "";
		const ociLabels = this.getOciLabels();

		let gccImage = `gcc:${gccVersion}`;
		if (this.langConfig?.versions) {
			const versionConfig = this.langConfig.versions.find((v: any) => v.value === gccVersion);
			if (versionConfig) {
				if (this.config.useAlpine && versionConfig.alpineImage) gccImage = versionConfig.alpineImage;
				else gccImage = versionConfig.image;
			}
		}

		const runtimeImage = this.config.useAlpine ? "alpine:latest" : "debian:bookworm-slim";
		const isAlpineUser = this.config.useAlpine ? "RUN adduser -D -u 1001 appuser && chown -R appuser:appuser /app" : "RUN useradd -r -u 1001 -g root appuser && chown -R appuser:root /app";

		return `# syntax=docker/dockerfile:1.4

# Build stage
FROM ${gccImage} AS build
WORKDIR /app
${this.config.useAlpine ? "RUN apk add --no-cache cmake make" : "RUN apt-get update && apt-get install -y --no-install-recommends cmake make && rm -rf /var/lib/apt/lists/*"}
COPY . .
# باگ 543: خطا دیگر پنهان نمیشه
RUN if [ -f CMakeLists.txt ]; then \\
        cmake -B build && cmake --build build -j$(nproc); \\
    elif [ -f Makefile ]; then \\
        make -j$(nproc); \\
    else \\
        g++ -o app main.cpp; \\
    fi

# Runtime stage
FROM ${runtimeImage}
WORKDIR /app
${this.config.useAlpine ? "RUN apk --no-cache add libstdc++" : "RUN apt-get update && apt-get install -y --no-install-recommends libstdc++6 && rm -rf /var/lib/apt/lists/*"}
${healthCheckInstall}
COPY --from=build /app/app* ./
${isAlpineUser}
USER appuser
${ociLabels}
EXPOSE ${this.config.port}${debugExpose}${healthCheck}
CMD ["./app"]`;
	}

	private generateCDockerfile(): string {
		const gccVersion = this.config.gccVersion || "13";
		const debugExpose = this.getDebugExpose();
		const healthCheck = this.getHealthCheck();
		const healthCheckInstall = this.config.enableHealthCheck ? `\n# Install health check tools\n${this.getInstallCommand()}\n` : "";
		const ociLabels = this.getOciLabels();

		let gccImage = `gcc:${gccVersion}`;
		if (this.langConfig?.versions) {
			const versionConfig = this.langConfig.versions.find((v: any) => v.value === gccVersion);
			if (versionConfig) {
				if (this.config.useAlpine && versionConfig.alpineImage) gccImage = versionConfig.alpineImage;
				else gccImage = versionConfig.image;
			}
		}

		const runtimeImage = this.config.useAlpine ? "alpine:latest" : "debian:bookworm-slim";
		const isAlpineUser = this.config.useAlpine ? "RUN adduser -D -u 1001 appuser && chown -R appuser:appuser /app" : "RUN useradd -r -u 1001 -g root appuser && chown -R appuser:root /app";

		return `# syntax=docker/dockerfile:1.4

# Build stage
FROM ${gccImage} AS build
WORKDIR /app
${this.config.useAlpine ? "RUN apk add --no-cache cmake make" : "RUN apt-get update && apt-get install -y --no-install-recommends cmake make && rm -rf /var/lib/apt/lists/*"}
COPY . .
# باگ 544: خطا دیگر پنهان نمیشه
RUN if [ -f CMakeLists.txt ]; then \\
        cmake -B build && cmake --build build -j$(nproc); \\
    elif [ -f Makefile ]; then \\
        make -j$(nproc); \\
    else \\
        gcc -o app main.c; \\
    fi

# Runtime stage
FROM ${runtimeImage}
WORKDIR /app
${this.config.useAlpine ? "RUN apk --no-cache add musl" : "RUN apt-get update && apt-get install -y --no-install-recommends libc6 && rm -rf /var/lib/apt/lists/*"}
${healthCheckInstall}
COPY --from=build /app/app* ./
${isAlpineUser}
USER appuser
${ociLabels}
EXPOSE ${this.config.port}${debugExpose}${healthCheck}
CMD ["./app"]`;
	}

	private generateGenericDockerfile(): string {
		const healthCheck = this.getHealthCheck();
		const healthCheckInstall = this.config.enableHealthCheck ? `\n# Install health check tools\n${this.getInstallCommand()}\n` : "";
		const ociLabels = this.getOciLabels();

		return `# syntax=docker/dockerfile:1.4

FROM ${this.config.useAlpine ? "alpine:latest" : "ubuntu:22.04"}
WORKDIR /app
${healthCheckInstall}
${this.config.useAlpine ? "RUN apk add --no-cache build-base git curl" : "RUN apt-get update && apt-get install -y --no-install-recommends build-essential git curl && rm -rf /var/lib/apt/lists/*"}
COPY . .
RUN if [ -f Makefile ]; then make; \\
    elif [ -f CMakeLists.txt ]; then cmake -B build && cmake --build build; \\
    elif [ -f package.json ]; then npm install && npm run build; \\
    elif [ -f requirements.txt ]; then pip install -r requirements.txt; fi
${ociLabels}
EXPOSE ${this.config.port}${healthCheck}
CMD ["sh", "-c", "echo 'Please configure your application startup command'"]`;
	}
}
