import { ProjectConfig } from "../types/index.js";

/**
 * GitLabCIGenerator class - Generates .gitlab-ci.yml
 */
export class GitLabCIGenerator {
	constructor(private config: ProjectConfig) {}

	generate(): string {
		const projectName = this.config.projectName;
		const jdkVersion = this.config.jdkVersion || "17";
		const mavenImage = this.getMavenImage(jdkVersion);
		const postgresVersion = this.getPostgresVersion();
		const dbName = this.getDbName();

		return `# GitLab CI/CD Pipeline for ${projectName}
# Generated by Dockeryzen

stages:
  - test
  - build
  - scan
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

# ============================================
# Test Stage
# ============================================
unit-test:
  stage: test
  image: ${mavenImage}
  services:
    - postgres:${postgresVersion}
  variables:
    POSTGRES_DB: ${dbName}
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: root
    DB_HOST: postgres
  script:
    - mvn test
  only:
    - merge_requests
    - develop
    - main

integration-test:
  stage: test
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t $DOCKER_IMAGE:test .
    - docker compose up -d
    - sleep 30
    - docker compose ps
    - docker compose down
  only:
    - merge_requests
    - develop

# ============================================
# Build Stage
# ============================================
build:
  stage: build
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHA $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
    - docker push $DOCKER_IMAGE:latest
  only:
    - main

# ============================================
# Security Scan Stage
# ============================================
security-scan:
  stage: scan
  image: aquasec/trivy:latest
  script:
    - trivy image --severity HIGH,CRITICAL --exit-code 1 $DOCKER_IMAGE:$CI_COMMIT_SHA
    - trivy image --severity HIGH,CRITICAL --format json --output trivy-results.json $DOCKER_IMAGE:$CI_COMMIT_SHA
  artifacts:
    reports:
      container_scanning: trivy-results.json
  only:
    - main

hadolint:
  stage: scan
  image: hadolint/hadolint:latest
  script:
    - hadolint Dockerfile
  only:
    - merge_requests
    - main

# ============================================
# Deploy Stage
# ============================================
deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl set image deployment/${projectName} app=$DOCKER_IMAGE:$CI_COMMIT_SHA
    - kubectl rollout status deployment/${projectName}
  environment:
    name: production
  only:
    - main
  when: manual

# ============================================
# Base Image Update Check
# ============================================
check-base-image:
  stage: scan
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker pull eclipse-temurin:${jdkVersion}-jre
    - docker pull postgres:${postgresVersion}
    - echo "Base images are up to date"
  only:
    - schedules`;
	}

	private getMavenImage(jdkVersion: string): string {
		if (jdkVersion === "8") {
			return "maven:3.9-eclipse-temurin-8";
		}
		return `maven:3.9-eclipse-temurin-${jdkVersion}`;
	}

	private getPostgresVersion(): string {
		const pg = this.config.databases.find((d) => d.type === "postgresql" || d.type === "timescaledb");
		return pg?.version || "17";
	}

	private getDbName(): string {
		const pg = this.config.databases.find((d) => d.type === "postgresql" || d.type === "timescaledb");
		return pg?.databaseName || "postgres";
	}
}
