import { ProjectConfig } from "../types/index.js";

export class GitLabCIGenerator {
	constructor(private config: ProjectConfig) {}

	generate(): string {
		const projectName = this.config.projectName;
		const lang = this.config.language;
		const buildImage = this.getBuildImage();
		const testCommand = this.getTestCommand();
		const services = this.generateServices();

		return `# GitLab CI/CD Pipeline for ${projectName}
# Generated by Dockeryzen

stages:
  - test
  - build
  - scan
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE

cache:
  paths:
    - target/
    - node_modules/
    - .m2/
    - .gradle/
    - vendor/
    - .bundle/

unit-test:
  stage: test
  image: ${buildImage}
${services ? `  services:\n${services}` : ""}
  script:
    - ${testCommand}
  only:
    - merge_requests
    - develop
    - main

integration-test:
  stage: test
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t $DOCKER_IMAGE:test .
    - apk add --no-cache docker-compose || true
    - docker compose up -d
    - sleep 30
    - docker compose ps
    - ${testCommand}
    - docker compose down
  only:
    - merge_requests
    - develop

build:
  stage: build
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHA $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
    - docker push $DOCKER_IMAGE:latest
  only:
    - main

security-scan:
  stage: scan
  image: aquasec/trivy:latest
  script:
    - trivy image --severity HIGH,CRITICAL --exit-code 1 $DOCKER_IMAGE:$CI_COMMIT_SHA
    - trivy image --severity HIGH,CRITICAL --format json --output trivy-results.json $DOCKER_IMAGE:$CI_COMMIT_SHA
  artifacts:
    reports:
      container_scanning: trivy-results.json
  only:
    - main

hadolint:
  stage: scan
  image: hadolint/hadolint:latest
  script:
    - hadolint Dockerfile
  only:
    - merge_requests
    - main

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - if command -v kubectl &> /dev/null; then
        kubectl set image deployment/${projectName} app=$DOCKER_IMAGE:$CI_COMMIT_SHA
        kubectl rollout status deployment/${projectName}
      else
        echo "kubectl not found, skipping deployment"
      fi
  environment:
    name: production
  only:
    - main
  when: on_success`;
	}

	private getBuildImage(): string {
		const lang = this.config.language;
		const buildTool = this.config.buildTool || "maven";
		const jdkVersion = this.config.jdkVersion || "17";
		const nodeVersion = this.config.nodeVersion || "18";
		const pythonVersion = this.config.pythonVersion || "3.11";
		const goVersion = this.config.goVersion || "1.21";
		const dotnetVersion = this.config.dotnetVersion || "8.0";
		const phpVersion = this.config.phpVersion || "8.3";
		const rubyVersion = this.config.rubyVersion || "3.3";
		// باگ 668: Rust version از config
		const rustVersion = this.config.rustVersion || "latest";

		if (lang.startsWith("java")) {
			if (buildTool === "gradle") {
				// باگ 588: gradle:7-jdk8 اصلاح شد
				if (jdkVersion === "8") {
					return "gradle:7-jdk8";
				}
				return `gradle:8-jdk${jdkVersion}`;
			}
			if (jdkVersion === "8") {
				return "maven:3.9-eclipse-temurin-8";
			}
			return `maven:3.9-eclipse-temurin-${jdkVersion}`;
		} else if (lang.startsWith("js")) {
			return `node:${nodeVersion}`;
		} else if (lang === "python") {
			return `python:${pythonVersion}`;
		} else if (lang === "go") {
			return `golang:${goVersion}`;
		} else if (lang === "dotnet") {
			return `mcr.microsoft.com/dotnet/sdk:${dotnetVersion}`;
		} else if (lang === "rust") {
			return `rust:${rustVersion}`;
		} else if (lang === "laravel") {
			return `php:${phpVersion}-cli`;
		} else if (lang === "rails") {
			return `ruby:${rubyVersion}`;
		}
		return "ubuntu:22.04";
	}

	private getTestCommand(): string {
		const lang = this.config.language;
		const buildTool = this.config.buildTool || "maven";

		if (lang.startsWith("java")) {
			if (buildTool === "gradle") {
				return "if [ -f gradlew ]; then ./gradlew test; else gradle test; fi";
			}
			return "if [ -f mvnw ]; then ./mvnw test; else mvn test; fi";
		} else if (lang.startsWith("js")) {
			const pm = this.config.packageManager || "npm";
			switch (pm) {
				case "yarn":
					return "yarn test";
				case "pnpm":
					return "pnpm test";
				case "bun":
					return "bun test";
				default:
					return "npm test";
			}
		} else if (lang === "python") {
			return "pytest || python -m pytest";
		} else if (lang === "go") {
			return "go test ./...";
		} else if (lang === "dotnet") {
			return "dotnet test";
		} else if (lang === "rust") {
			return "cargo test";
		} else if (lang === "laravel") {
			return "php artisan test";
		} else if (lang === "rails") {
			return "bundle exec rspec";
		}
		return "echo 'No test command defined'";
	}

	private generateServices(): string {
		const services: string[] = [];

		for (const db of this.config.databases) {
			if (db.useExternalUrl) continue;

			if (db.type === "postgresql" || db.type === "timescaledb") {
				services.push(`    - postgres:${db.version || "17"}`);
			} else if (db.type === "mysql") {
				services.push(`    - mysql:${db.version || "8"}`);
			} else if (db.type === "mariadb") {
				services.push(`    - mariadb:${db.version || "11"}`);
			} else if (db.type === "mongodb") {
				services.push(`    - mongo:${db.version || "8"}`);
			} else if (db.type === "redis") {
				services.push(`    - redis:${db.version || "8"}-alpine`);
			} else if (db.type === "cockroachdb") {
				// باگ 589: CockroachDB اضافه شد
				services.push(`    - cockroachdb/cockroach:${db.version || "v24.3"}`);
			}
		}

		if (this.config.enableRedis && !this.config.databases.some((d) => d.type === "redis")) {
			services.push(`    - redis:8-alpine`);
		}

		// باگ 587: indent اصلاح شد
		return services.join("\n");
	}
}
