import { ProjectConfig } from "../types/index.js";
import { sanitizeName } from "../utils/helpers.js";

export class NginxConfigGenerator {
	constructor(private config: ProjectConfig) {}

	generate(): string {
		// باگ 591 و 631: استفاده از sanitizeName
		const projectName = sanitizeName(this.config.projectName);
		const port = this.config.port;

		return `# Nginx configuration for ${this.config.projectName}
# Generated by Dockeryzen

server {
    # باگ 669: server_name قابل تنظیم
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php index.html;

    # Logs
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Gzip
    gzip on;
    gzip_min_length 1000;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";

    # Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM
    # باگ 592: regex اصلاح شد
    location ~ \.php$ {
        fastcgi_pass ${projectName}:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Static files
    # باگ 592: regex اصلاح شد
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|woff|woff2|ttf|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Deny access to sensitive files
    # باگ 592: regex اصلاح شد
    location ~ /\. {
        deny all;
    }
}
`;
	}
}
