import { ProjectConfig } from "../types/index.js";
import { sanitizeName } from "../utils/helpers.js";

export class NginxConfigGenerator {
	constructor(private config: ProjectConfig) {}

	generate(): string {
		// ✅ Fix: اسم سرویس جدا از projectName
		const serviceName = (this.config as any).serviceName || sanitizeName(this.config.projectName) || "app";
		const serverName = (this.config as any).domain || "_";
		const clientMaxBodySize = (this.config as any).clientMaxBodySize || "100M";
		const fastcgiTimeout = (this.config as any).fastcgiTimeout || "300s";
		const publicPath = "/var/www/html/public";

		return `# Nginx configuration for ${this.config.projectName}
# Generated by Dockeryzen
# https://github.com/dockeryzen

server {
    # ✅ Fix: server_name قابل تنظیم (پیش‌فرض _ برای catch-all)
    listen 80;
    server_name ${serverName};
    root ${publicPath};
    index index.php;

    # ✅ Fix: لاگ‌ها به stdout/stderr برای docker logs
    access_log /dev/stdout;
    error_log /dev/stderr warn;

    # ✅ Fix: حجم بدنه درخواست
    client_max_body_size ${clientMaxBodySize};

    # Gzip
    gzip on;
    gzip_min_length 1000;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
    gzip_disable "msie6";

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM
    # ✅ Fix: اسم سرویس قابل تنظیم
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass ${serviceName}:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS $https if_not_empty;
        fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
        include fastcgi_params;

        # ✅ Fix: timeout برای درخواست‌های طولانی
        fastcgi_read_timeout ${fastcgiTimeout};
        fastcgi_send_timeout ${fastcgiTimeout};
        fastcgi_connect_timeout ${fastcgiTimeout};

        # ✅ Fix: buffer tuning
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    # Static files
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|woff|woff2|ttf|svg|webp|avif)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
        try_files $uri =404;
    }

    # ✅ Fix: deny فایل‌های مخفی به جز .well-known (برای Let's Encrypt)
    location ~ /\.(?!well-known).* {
        deny all;
        access_log off;
        log_not_found off;
    }

    # ✅ Fix: deny دسترسی به فایل‌های حساس Laravel
    location ~* (\.env|\.git|composer\.(json|lock)|package\.(json|lock)|artisan|\.htaccess)$ {
        deny all;
        access_log off;
        log_not_found off;
    }

    # ✅ Fix: deny دسترسی مستقیم به storage و vendor
    location ~ ^/(storage|vendor|bootstrap|config|database|resources|routes|tests)/ {
        deny all;
        access_log off;
        log_not_found off;
    }
}
`;
	}
}
