import { ProjectConfig } from "../types/index.js";

/**
 * PrometheusConfigGenerator class - Generates prometheus.yml
 * Fix bugs: 475, 482
 */
export class PrometheusConfigGenerator {
	constructor(private config: ProjectConfig) {}

	generate(): string {
		const projectName = this.config.projectName;
		const port = this.config.port;
		const scrapeConfigs: string[] = [];

		// Main app scrape config
		if (this.config.enableHealthCheck) {
			const healthPath = this.config.healthCheckPath || "/health";
			const metricsPath = healthPath.includes("actuator") ? "/actuator/prometheus" : "/metrics";

			scrapeConfigs.push(`  - job_name: '${projectName}'
    metrics_path: '${metricsPath}'
    static_configs:
      - targets: ['${projectName}:${port}']`);
		}

		// Database scrape configs
		for (const db of this.config.databases) {
			if (db.useExternalUrl) continue;

			const serviceName = `${projectName}-${db.type}`;

			if (db.type === "postgresql" || db.type === "timescaledb") {
				scrapeConfigs.push(`
  - job_name: '${serviceName}'
    static_configs:
      - targets: ['${serviceName}:${db.internalPort}']`);
			} else if (db.type === "redis") {
				scrapeConfigs.push(`
  - job_name: '${serviceName}'
    static_configs:
      - targets: ['${serviceName}:${db.internalPort}']`);
			} else if (db.type === "elasticsearch") {
				scrapeConfigs.push(`
  - job_name: '${serviceName}'
    static_configs:
      - targets: ['${serviceName}:${db.internalPort}']`);
			}
		}

		return `# Prometheus configuration for ${projectName}
# Generated by Dockeryzen

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
${scrapeConfigs.join("\n")}
`;
	}
}
