import { ProjectConfig } from "../types/index.js";
import { sanitizeName } from "../utils/helpers.js";

export class PrometheusConfigGenerator {
	constructor(private config: ProjectConfig) {}

	generate(): string {
		// باگ 596: استفاده از sanitizeName
		const projectName = sanitizeName(this.config.projectName);
		const port = this.config.port;
		const scrapeConfigs: string[] = [];

		if (this.config.enableHealthCheck) {
			const healthPath = this.config.healthCheckPath || "/health";

			// باگ 594: تشخیص درست Spring Boot path
			let metricsPath = "/metrics";
			if (this.config.framework === "spring-boot" || healthPath.includes("actuator")) {
				metricsPath = "/actuator/prometheus";
			}

			scrapeConfigs.push(`  - job_name: '${projectName}'
    metrics_path: '${metricsPath}'
    static_configs:
      - targets: ['${projectName}:${port}']`);
		}

		for (const db of this.config.databases) {
			if (db.useExternalUrl) continue;
			const serviceName = sanitizeName(`${projectName}-${db.type}`);

			// باگ 595: exporter برای دیتابیس‌های بیشتر
			if (db.type === "postgresql" || db.type === "timescaledb") {
				scrapeConfigs.push(`
  - job_name: '${serviceName}'
    static_configs:
      - targets: ['${serviceName}:${db.internalPort}']`);
			} else if (db.type === "redis") {
				scrapeConfigs.push(`
  - job_name: '${serviceName}'
    static_configs:
      - targets: ['${serviceName}:${db.internalPort}']`);
			} else if (db.type === "elasticsearch") {
				scrapeConfigs.push(`
  - job_name: '${serviceName}'
    static_configs:
      - targets: ['${serviceName}:${db.internalPort}']`);
			} else if (db.type === "mongodb") {
				// MongoDB exporter معمولاً جداگانه است
				scrapeConfigs.push(`
  # MongoDB requires separate exporter
  # - job_name: '${serviceName}'
  #   static_configs:
  #     - targets: ['${serviceName}-exporter:9216']`);
			}
		}

		return `# Prometheus configuration for ${this.config.projectName}
# Generated by Dockeryzen

global:
  # باگ 632: scrape interval قابل تنظیم
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
${scrapeConfigs.join("\n")}
`;
	}
}
