import * as vscode from "vscode";
import * as path from "path";
import * as fs from "fs";
import { ConfigLoader, FacetConfig } from "./configLoader.js";
import { PathResolver } from "./pathResolver.js";

export class FileGenerator {
	constructor(
		private context: vscode.ExtensionContext,
		private configLoader: ConfigLoader,
	) {}

	async generateFile(language: string, facetKey: string, version: string): Promise<boolean> {
		try {
			const config = this.configLoader.getFacetConfig(language, facetKey);

			if (!config) {
				throw new Error(`Configuration not found for ${language}.${facetKey}`);
			}

			if (!config.version[version]) {
				throw new Error(`Version ${version} not found for ${language}.${facetKey}`);
			}

			// Get workspace root
			const workspaceFolders = vscode.workspace.workspaceFolders;
			if (!workspaceFolders) {
				throw new Error("No workspace folder open");
			}

			const workspaceRoot = workspaceFolders[0].uri.fsPath;
			const fileName = `${config.name}${config.extension}`;

			// Resolve the default path
			const defaultPath = PathResolver.resolvePath(workspaceRoot, config.route, fileName);

			// Show dialog for path selection
			const finalPath = await PathResolver.showFileDialog(path.dirname(defaultPath), fileName);

			if (!finalPath) {
				return false; // User cancelled
			}

			// Generate content from template
			const content = await this.loadTemplateContent(language, facetKey, config, version);

			// Ensure directory exists and write file
			PathResolver.ensureDirectory(finalPath);

			// Check if path is versioned and inform user
			if (finalPath !== path.join(path.dirname(defaultPath), fileName)) {
				vscode.window.showInformationMessage(`ℹ️ File already exists. Created as: ${path.basename(finalPath)}`);
			}

			// Write the file
			fs.writeFileSync(finalPath, content, "utf-8");

			// Open the file in editor
			const document = await vscode.workspace.openTextDocument(finalPath);
			await vscode.window.showTextDocument(document);

			// Show success message
			vscode.window.showInformationMessage(`✅ Successfully generated ${fileName}`);

			return true;
		} catch (error) {
			vscode.window.showErrorMessage(`Failed to generate file: ${error instanceof Error ? error.message : error}`);
			return false;
		}
	}

	private async loadTemplateContent(language: string, facetKey: string, config: FacetConfig, version: string): Promise<string> {
		const templatePath = config.version[version];

		if (!templatePath) {
			return this.getDefaultTemplate(language, config, version);
		}

		// Resolve template path
		const fullTemplatePath = path.join(this.context.extensionPath, templatePath.replace("./", ""));

		try {
			if (fs.existsSync(fullTemplatePath)) {
				// Clear require cache for hot reload
				delete require.cache[require.resolve(fullTemplatePath)];

				const templateModule = require(fullTemplatePath);

				// Try different export patterns
				if (typeof templateModule.generate === "function") {
					return templateModule.generate({
						language,
						facetKey,
						config,
						version,
						timestamp: new Date().toISOString(),
					});
				}

				if (typeof templateModule.default === "function") {
					return templateModule.default({
						language,
						facetKey,
						config,
						version,
						timestamp: new Date().toISOString(),
					});
				}

				// If it's a string, return directly
				if (typeof templateModule === "string") {
					return templateModule;
				}

				if (typeof templateModule.default === "string") {
					return templateModule.default;
				}
			}
		} catch (error) {
			console.warn(`Failed to load template: ${templatePath}`, error);
		}

		return this.getDefaultTemplate(language, config, version);
	}

	private getDefaultTemplate(language: string, config: FacetConfig, version: string): string {
		const header = `# Generated by Code Facet Generator
# Language: ${language}
# Type: ${config.name}
# Version: ${version}
# Date: ${new Date().toLocaleString()}
`;

		const templates: { [key: string]: string } = {
			java: `${header}
<?xml version="1.0" encoding="UTF-8"?>
<configuration version="${version}">
    <!-- Add your ${config.name} configuration here -->
</configuration>`,

			javascript: `${header}
{
  "name": "${config.name}",
  "version": "${version}",
  "description": "${config.description}",
  "main": "index.js",
  "scripts": {
    "test": "echo \\"Error: no test specified\\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}`,

			csharp: `${header}
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>${version}</TargetFramework>
  </PropertyGroup>
</Project>`,

			default: `${header}
# Configuration for ${config.name}
# Generated with version ${version}
`,
		};

		return templates[language.toLowerCase()] || templates.default;
	}
}
